services:
  backend:
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    build:
      context: ./backend
    container_name: instagram-clone-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/instagram/:/home/instagram

  frontend:
    stdin_open: true
    tty: true
    build:
      context: ./frontend
    container_name: instagram-clone-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/instagram/:/home/instagram

  db:
    image: mariadb:lts
    container_name: instagram-clone-db
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=instagram_db
      - MARIADB_USER=instagram_user
      - MARIADB_PASSWORD=instagram_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local
